# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: 📝 校订现有事件
description: 发现了现有历史事件数据的错误，想要提交修正建议
title: "[校订] "
labels: ["校订", "待审核"]
assignees:
  - sansan0
body:
  - type: markdown
    attributes:
      value: |
        感谢你的细心！每一个错误的发现和修正都让这个历史数据库更加准确。

        📚 **请确保有可靠的史料依据支撑你的修正建议**

  - type: input
    id: event-date
    attributes:
      label: 📅 事件发生的年份/日期
      description: 请填写你要修改的事件的日期，方便我们定位
      placeholder: 如：1921-07-23 或 1921年7月
    validations:
      required: true

  - type: checkboxes
    id: problem-type
    attributes:
      label: 🔍 问题类型
      description: 请选择发现的问题类型（可多选）
      options:
        - label: 📅 日期错误
        - label: 📍 地点错误
        - label: 📄 事件描述错误
        - label: 🏷️ 事件类型错误
        - label: 📚 史料来源错误
        - label: 🔢 年龄计算错误

  - type: textarea
    id: original-data
    attributes:
      label: ❌ 原始数据（你看到的错误信息）
      description: 请描述当前在地图上看到的错误数据
      placeholder: |
        例如：
        - 日期：1921年7月
        - 地点：上海
        - 描述：参加中共一大
        - 问题：地点不够精确
    validations:
      required: true

  - type: textarea
    id: suggested-correction
    attributes:
      label: ✅ 建议修改为
      description: 请提供你认为正确的信息
      placeholder: |
        例如：
        - 日期：1921年7月23日
        - 地点：上海法租界望志路106号（今兴业路76号）
        - 描述：出席中国共产党第一次全国代表大会开幕会议
    validations:
      required: true

  - type: textarea
    id: source-verification
    attributes:
      label: 📖 史料依据（最重要！）
      description: 请提供可靠的史料来源支持你的修正
      placeholder: |
        例如：
        《毛泽东年谱（1893-1949）》上卷，中央文献出版社，2013年12月第2版，第86页。

        💡 如果可以的话，强烈建议附上史料的截图或照片
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: 💭 补充说明（可选）
      description: 还有什么想要补充的吗？
      placeholder: 你可以分享发现这个问题的过程，或者对这段历史的感想...

  - type: checkboxes
    id: verification-checklist
    attributes:
      label: ✅ 提交前自查
      description: 请确认以下几点
      options:
        - label: 我已经仔细核对了史料来源
          required: true
        - label: 我确信这个修正在历史学上是准确的
          required: true
        - label: 我理解这个修正会影响地图显示的准确性
          required: true
