# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: ➕ 增补缺失事件
description: 发现了重要的历史事件遗漏，想要补充到地图中
title: "[新增] "
labels: ["新增", "待审核"]
assignees:
  - sansan0
body:
  - type: markdown
    attributes:
      value: |
        感谢你的贡献！每一个重要历史事件的补充都让这张地图更加完整。

        📍 **请确保这个事件涉及明确的地理移动且具有历史重要性**

  - type: input
    id: event-date
    attributes:
      label: 📅 事件日期
      description: 事件发生的具体日期
      placeholder: 如：1927-09-09
    validations:
      required: true

  - type: input
    id: event-location
    attributes:
      label: 📍 事件地点
      description: 事件发生的地理位置
      placeholder: 如：湖南省浏阳市
    validations:
      required: true

  - type: textarea
    id: event-description
    attributes:
      label: 📝 事件简述
      description: 用一句话简明扼要地描述发生了什么
      placeholder: 如：领导湘赣边界秋收起义
    validations:
      required: true

  - type: dropdown
    id: importance-level
    attributes:
      label: ⭐ 重要性级别
      description: 根据贡献指南评估这个事件的历史重要性
      options:
        - 🔴 一级事件（历史主干 - 里程碑式转折点）
        - 🟡 二级事件（关键枝干 - 承上启下的重要节点）
        - ⚪ 三级事件（枝叶细节 - 丰富历史细节的常规活动）
    validations:
      required: true

  - type: dropdown
    id: movement-type
    attributes:
      label: 🚗 事件类型
      description: 根据地理移动特征选择事件类型
      options:
        - 出生
        - 国际移动
        - 长途移动
        - 短途移动
        - 原地活动
    validations:
      required: true

  - type: textarea
    id: detailed-description
    attributes:
      label: 📋 详细描述
      description: 详细描述这个事件的历史背景和重要意义
      placeholder: |
        请详细描述：
        1. 事件的具体经过
        2. 历史背景和重要意义
        3. 涉及的地理移动路线（如果有的话）
    validations:
      required: true

  - type: textarea
    id: source-verification
    attributes:
      label: 📖 史料依据（最重要！）
      description: 请提供可靠的史料来源
      placeholder: |
        例如：
        《毛泽东传》金冲及主编，中央文献出版社，2016年修订版，第150-155页。

        💡 如果可以的话，强烈建议附上史料的截图或照片
    validations:
      required: true

  - type: checkboxes
    id: addition-criteria
    attributes:
      label: 📏 录入标准自查
      description: 请确认这个事件符合项目录入标准
      options:
        - label: 涉及明确的地理移动或地点变化
          required: true
        - label: 具有相应级别的历史重要性
          required: true
        - label: 史料来源可供查证和验证
          required: true
        - label: 不与现有事件重复
          required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: 💭 补充说明或感言（可选）
      description: 还想分享什么吗？
      placeholder: |
        你可以分享：
        - 发现这个遗漏事件的过程
        - 对这段历史的个人感想
        - 为什么认为这个事件很重要
        - 或者其他任何想说的...
