# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: 🐛 Bug 报告
description: 发现了地图功能的问题或错误
title: "[Bug] "
labels: ["bug"]
assignees:
  - sansan0
body:
  - type: markdown
    attributes:
      value: |
        感谢你的反馈！详细的bug报告帮助我们快速定位和修复问题。

  - type: dropdown
    id: bug-category
    attributes:
      label: 🏷️ 问题类型
      options:
        - 地图显示异常
        - 播放控制功能失效
        - 数据加载错误
        - 移动端适配问题
        - 性能问题
        - 其他功能问题
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 📝 问题描述
      description: 请详细描述遇到的问题
      placeholder: 清楚地描述发生了什么问题...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 复现步骤
      description: 如何重现这个问题？
      placeholder: |
        1. 打开地图页面
        2. 点击播放按钮
        3. 发现...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ 期望的行为
      description: 你期望发生什么？
      placeholder: 描述正常情况下应该发生什么...
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: 📱 设备类型
      options:
        - PC/笔记本电脑
        - 手机
        - 平板电脑
    validations:
      required: true

  - type: input
    id: browser-info
    attributes:
      label: 🌐 浏览器信息
      description: 使用的浏览器和版本
      placeholder: 如：Chrome 119.0.0.0, Safari 17.0, Firefox 120.0
    validations:
      required: true

  - type: input
    id: screen-resolution
    attributes:
      label: 📺 屏幕分辨率（可选）
      description: 如果是显示相关问题，请提供屏幕分辨率
      placeholder: 如：1920x1080, 375x667

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 其他信息
      description: 还有什么可能有用的信息吗？
      placeholder: |
        - 截图或录屏
        - 控制台错误信息
        - 网络状况
        - 其他相关信息...
