# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: 💡 功能建议
description: 提出新功能想法或改进建议
title: "[功能] "
labels: ["enhancement"]
assignees:
  - sansan0
body:
  - type: markdown
    attributes:
      value: |
        感谢你的创意！好的想法让这个项目变得更好。

  - type: dropdown
    id: feature-category
    attributes:
      label: 🏷️ 功能类别
      options:
        - 地图交互优化
        - 数据展示改进
        - 新的数据维度
        - 用户体验提升
        - 性能优化
        - 移动端体验
        - 教育功能
        - 其他
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: 💭 功能描述
      description: 详细描述你希望添加的功能
      placeholder: 清楚地描述你想要的功能...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 🎯 使用场景
      description: 这个功能会在什么情况下被使用？
      placeholder: |
        例如：
        - 当用户想要...的时候
        - 在...场景下会很有用
        - 可以帮助用户...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 建议方案
      description: 你觉得可以怎么实现这个功能？
      placeholder: |
        如果你有具体的实现想法，欢迎分享：
        - UI/UX 设计想法
        - 技术实现思路
        - 参考其他类似应用
        - 等等...

  - type: dropdown
    id: priority
    attributes:
      label: ⭐ 优先级评估
      description: 你认为这个功能的重要程度如何？
      options:
        - 高 - 非常重要，强烈建议添加
        - 中 - 会很有用，建议考虑
        - 低 - 锦上添花，有时间的话可以做
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 其他补充
      description: 还有什么想说的吗？
      placeholder: |
        - 相关的截图或示例
        - 类似功能的参考链接
        - 其他相关想法
        - 等等...
