# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: false
contact_links:
  - name: 📖 查看贡献指南
    url: https://github.com/sansan0/mao-map#-邀你共绘历史画卷
    about: 查看详细的贡献指南和数据规范
  - name: 💬 交流讨论
    url: https://github.com/sansan0/mao-map/discussions
    about: 非正式讨论、想法分享或一般性问题
